### ISSUE TITLE
About the dataset for cnibp

### ISSUE THREAD

**Issue by choi3897** [remotebiosensing/rppg#50]
Hello, I'm interested in your research.
I am wondering if it would be possible to obtain a dataset to train CNIBP ?

**Comment by SpicyYeol** [comment]
Hi, Choi.

Do you mean you want to obtain a dataset for training vid to CNIBP (Continuous Non-Invasive Blood Pressure) or ppg to CNIBP?

If you want to obtain a dataset for vid to CNIBP, please request and receive the V4V dataset.

If you want to obtain a dataset for ppg to CNIBP, please request the MIMIC4 dataset.
