### ISSUE TITLE
some question about interpreting result.csv file in the path of [rppg/result/csv/result.csv]

### ISSUE THREAD

**Issue by aytekin827** [remotebiosensing/rppg#53]
Hello. 

I have some question for in the file at [rppg/result/csv/result.csv]

1. what does each column mean in 'result.csv' file?

  [example]
  row : 'BigSmall_PURE_PURE_72_30_10' 
  used model : BigSmall
  training dataset : PURE
  test dataset : PURE
  Image Sise : 72
  EVAL_TIME_LENGTH : 30
  ??? : 10
  
  - what does the 10 mean in this row? 
  - and the other is right?

2. All of the model combinations are trained and tested by your teams? 

3. How can I read 'calc_comp.csv'file?
I found all the file in this repository but cannot found any description about this.

Thank you and your team for this great job!!

**Comment by paperchae** [comment]
Hey!

Thanks for your interest.

The last column supposed to mean the epochs for traing.

Sorry for the confusion LOL

Hope you have a great day!

John chae

**Comment by SpicyYeol** [comment]
I apologize, the answer to the first question was correct jongeui's one.

2023년 8월 9일 (수) 오후 6:59, Kim Dae Yeol ***@***.***>님이 작성:

**Comment by aytekin827** [comment]
thanks very much for help!
