### ISSUE TITLE
Help using model on another dataset

### ISSUE THREAD

**Issue by MRasyidUlwan** [remotebiosensing/rppg#9]
Hello thank you for your work, I'm planning on using PhysNet_2DCNN_LSTM, but I can't get it run somehow.. can you provide helpful steps? much appreciated. and can you please provide a pretrained model? the one that has been shared can't be accessed anymore

**Comment by TVS-AI** [comment]
Sorry for the late reply.
I will update all source code so that it can work comfortably.

We will update README soon
